.TH "Tesira_DSP_EPI.MeterMetadata" 3 "Wed Aug 5 2020" "Version 2.0.0.x" "Biamp Tesira Essentials Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tesira_DSP_EPI.MeterMetadata
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBMeterMimimum\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "double \fBMeterMaxiumum\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBDefaultPollTime\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Biamp Tesira Essentials Plugin from the source code\&.
