.TH "Tesira_DSP_EPI.TesiraDspPropertiesConfig" 3 "Wed Aug 5 2020" "Version 2.0.0.x" "Biamp Tesira Essentials Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tesira_DSP_EPI.TesiraDspPropertiesConfig
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "CommunicationMonitorConfig \fBCommunicationMonitorProperties\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "EssentialsControlPropertiesConfig \fBControl\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBTesiraFaderControlBlockConfig\fP > \fBFaderControlBlocks\fP\fC [get, set]\fP"
.br
.RI "These are key-value pairs, uint id, string type\&. 
.br
 Valid types are level and mute\&. Need to include the index values somehow "
.ti -1c
.RI "Dictionary< string, \fBTesiraDialerControlBlockConfig\fP > \fBDialerControlBlocks\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBTesiraSwitcherControlBlockConfig\fP > \fBSwitcherControlBlocks\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< uint, \fBTesiraDspPresets\fP > \fBPresets\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBTesiraStateControlBlockConfig\fP > \fBStateControlBlocks\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBTesiraMeterBlockConfig\fP > \fBMeterControlBlocks\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBTesiraCrosspointStateBlockConfig\fP > \fBCrosspointStateControlBlocks\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBTesiraRoomCombinerBlockConfig\fP > \fBRoomCombinerControlBlocks\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "Dictionary<string, \fBTesiraFaderControlBlockConfig\fP> Tesira_DSP_EPI\&.TesiraDspPropertiesConfig\&.FaderControlBlocks\fC [get]\fP, \fC [set]\fP"

.PP
These are key-value pairs, uint id, string type\&. 
.br
 Valid types are level and mute\&. Need to include the index values somehow 

.SH "Author"
.PP 
Generated automatically by Doxygen for Biamp Tesira Essentials Plugin from the source code\&.
