.TH "Tesira_DSP_EPI.TesiraDspDeviceInfo" 3 "Wed Aug 5 2020" "Version 2.0.0.x" "Biamp Tesira Essentials Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tesira_DSP_EPI.TesiraDspDeviceInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits EssentialsBridgeableDevice\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTesiraDspDeviceInfo\fP (string key, string name, \fBTesiraDsp\fP parent, Dictionary< uint, \fBTesiraDspPresets\fP > presets)"
.br
.RI "Constructor for Device Info Object "
.ti -1c
.RI "override void \fBLinkToApi\fP (BasicTriList trilist, uint joinStart, string joinMapKey, EiscApiAdvanced bridge)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FeedbackCollection< Feedback > \fBFeedbacks\fP"
.br
.RI "Feedback Collection for Component "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "StringFeedback \fBNameFeedback\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Tesira_DSP_EPI\&.TesiraDspDeviceInfo\&.TesiraDspDeviceInfo (string key, string name, \fBTesiraDsp\fP parent, Dictionary< uint, \fBTesiraDspPresets\fP > presets)"

.PP
Constructor for Device Info Object 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP Unique Key
.br
\fIname\fP Friendly Name
.br
\fIparent\fP Parent Device
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "FeedbackCollection<Feedback> Tesira_DSP_EPI\&.TesiraDspDeviceInfo\&.Feedbacks"

.PP
Feedback Collection for Component 

.SH "Author"
.PP 
Generated automatically by Doxygen for Biamp Tesira Essentials Plugin from the source code\&.
