.TH "Tesira_DSP_EPI.TesiraDspCrosspointState" 3 "Wed Aug 5 2020" "Version 2.0.0.x" "Biamp Tesira Essentials Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tesira_DSP_EPI.TesiraDspCrosspointState
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTesira_DSP_EPI\&.TesiraDspControlPoint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTesiraDspCrosspointState\fP (string key, \fBTesiraCrosspointStateBlockConfig\fP config, \fBTesiraDsp\fP parent)"
.br
.RI "Constructor for Tesira DSP Matrix Mixer Component "
.ti -1c
.RI "void \fBGetState\fP ()"
.br
.RI "Poll Component State Value "
.ti -1c
.RI "void \fBStateOn\fP ()"
.br
.RI "Set Component State to On "
.ti -1c
.RI "void \fBStateOff\fP ()"
.br
.RI "Set Component State to Off "
.ti -1c
.RI "void \fBStateToggle\fP ()"
.br
.RI "Toggle Component State "
.ti -1c
.RI "override void \fBParseGetMessage\fP (string attributeCode, string message)"
.br
.RI "Parse non-subscription data "
.ti -1c
.RI "override void \fBLinkToApi\fP (BasicTriList trilist, uint joinStart, string joinMapKey, EiscApiAdvanced bridge)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly string \fBAttributeCode\fP = 'crosspointLevelState'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "BoolFeedback \fBCrosspointStateFeedback\fP\fC [get, set]\fP"
.br
.RI "Boolean Feedback for Component State "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Tesira_DSP_EPI\&.TesiraDspCrosspointState\&.TesiraDspCrosspointState (string key, \fBTesiraCrosspointStateBlockConfig\fP config, \fBTesiraDsp\fP parent)"

.PP
Constructor for Tesira DSP Matrix Mixer Component 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP Unique Key for Component
.br
\fIconfig\fP Config Object for Component
.br
\fIparent\fP Parent object of Component
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Tesira_DSP_EPI\&.TesiraDspCrosspointState\&.GetState ()"

.PP
Poll Component State Value 
.SS "override void Tesira_DSP_EPI\&.TesiraDspCrosspointState\&.ParseGetMessage (string attributeCode, string message)\fC [virtual]\fP"

.PP
Parse non-subscription data 
.PP
\fBParameters\fP
.RS 4
\fIattributeCode\fP Attribute code of Component
.br
\fImessage\fP Data to parse
.RE
.PP

.PP
Reimplemented from \fBTesira_DSP_EPI\&.TesiraDspControlPoint\fP\&.
.SS "void Tesira_DSP_EPI\&.TesiraDspCrosspointState\&.StateOff ()"

.PP
Set Component State to Off 
.SS "void Tesira_DSP_EPI\&.TesiraDspCrosspointState\&.StateOn ()"

.PP
Set Component State to On 
.SS "void Tesira_DSP_EPI\&.TesiraDspCrosspointState\&.StateToggle ()"

.PP
Toggle Component State 
.SH "Property Documentation"
.PP 
.SS "BoolFeedback Tesira_DSP_EPI\&.TesiraDspCrosspointState\&.CrosspointStateFeedback\fC [get]\fP, \fC [set]\fP"

.PP
Boolean Feedback for Component State 

.SH "Author"
.PP 
Generated automatically by Doxygen for Biamp Tesira Essentials Plugin from the source code\&.
