.TH "Tesira_DSP_EPI.TesiraDspStateControl" 3 "Wed Aug 5 2020" "Version 2.0.0.x" "Biamp Tesira Essentials Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tesira_DSP_EPI.TesiraDspStateControl
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTesira_DSP_EPI\&.TesiraDspControlPoint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTesiraDspStateControl\fP (string key, \fBTesiraStateControlBlockConfig\fP config, \fBTesiraDsp\fP parent)"
.br
.RI "Constructor for StateControl Component "
.ti -1c
.RI "override void \fBSubscribe\fP ()"
.br
.RI "Subscribe to component "
.ti -1c
.RI "override void \fBUnsubscribe\fP ()"
.br
.RI "Unsubscribe from component "
.ti -1c
.RI "void \fBParseSubscriptionMessage\fP (string customName, string value)"
.br
.RI "Parses subscription-related responses "
.ti -1c
.RI "override void \fBParseGetMessage\fP (string attributeCode, string message)"
.br
.RI "Parses a non subscription response "
.ti -1c
.RI "void \fBGetState\fP ()"
.br
.RI "Poll state status "
.ti -1c
.RI "void \fBStateOn\fP ()"
.br
.RI "Set State On "
.ti -1c
.RI "void \fBStateOff\fP ()"
.br
.RI "Set State off "
.ti -1c
.RI "void \fBStateToggle\fP ()"
.br
.RI "Toggle State value "
.ti -1c
.RI "override void \fBLinkToApi\fP (BasicTriList trilist, uint joinStart, string joinMapKey, EiscApiAdvanced bridge)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "BoolFeedback \fBStateFeedback\fP\fC [get, set]\fP"
.br
.RI "Boolean Feedback for State Value "
.ti -1c
.RI "string \fBStateCustomName\fP\fC [get, set]\fP"
.br
.RI "State Subscription Identifier "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Tesira_DSP_EPI\&.TesiraDspStateControl\&.TesiraDspStateControl (string key, \fBTesiraStateControlBlockConfig\fP config, \fBTesiraDsp\fP parent)"

.PP
Constructor for StateControl Component 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP Unique Key for Component
.br
\fIconfig\fP Config Object for Component
.br
\fIparent\fP Component Parent Object
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Tesira_DSP_EPI\&.TesiraDspStateControl\&.GetState ()"

.PP
Poll state status 
.SS "override void Tesira_DSP_EPI\&.TesiraDspStateControl\&.ParseGetMessage (string attributeCode, string message)\fC [virtual]\fP"

.PP
Parses a non subscription response 
.PP
\fBParameters\fP
.RS 4
\fIattributeCode\fP The attribute code of the command
.br
\fImessage\fP The message to parse
.RE
.PP

.PP
Reimplemented from \fBTesira_DSP_EPI\&.TesiraDspControlPoint\fP\&.
.SS "void Tesira_DSP_EPI\&.TesiraDspStateControl\&.ParseSubscriptionMessage (string customName, string value)"

.PP
Parses subscription-related responses 
.PP
\fBParameters\fP
.RS 4
\fIcustomName\fP Subscription identifier
.br
\fIvalue\fP response data to be parsed
.RE
.PP

.SS "void Tesira_DSP_EPI\&.TesiraDspStateControl\&.StateOff ()"

.PP
Set State off 
.SS "void Tesira_DSP_EPI\&.TesiraDspStateControl\&.StateOn ()"

.PP
Set State On 
.SS "void Tesira_DSP_EPI\&.TesiraDspStateControl\&.StateToggle ()"

.PP
Toggle State value 
.SS "override void Tesira_DSP_EPI\&.TesiraDspStateControl\&.Subscribe ()\fC [virtual]\fP"

.PP
Subscribe to component 
.PP
Reimplemented from \fBTesira_DSP_EPI\&.TesiraDspControlPoint\fP\&.
.SS "override void Tesira_DSP_EPI\&.TesiraDspStateControl\&.Unsubscribe ()\fC [virtual]\fP"

.PP
Unsubscribe from component 
.PP
Reimplemented from \fBTesira_DSP_EPI\&.TesiraDspControlPoint\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Tesira_DSP_EPI\&.TesiraDspStateControl\&.StateCustomName\fC [get]\fP, \fC [set]\fP"

.PP
State Subscription Identifier 
.SS "BoolFeedback Tesira_DSP_EPI\&.TesiraDspStateControl\&.StateFeedback\fC [get]\fP, \fC [set]\fP"

.PP
Boolean Feedback for State Value 

.SH "Author"
.PP 
Generated automatically by Doxygen for Biamp Tesira Essentials Plugin from the source code\&.
