.TH "Tesira_DSP_EPI.TesiraFaderControlBlockConfig" 3 "Wed Aug 5 2020" "Version 2.0.0.x" "Biamp Tesira Essentials Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tesira_DSP_EPI.TesiraFaderControlBlockConfig
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBEnabled\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBLabel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBLevelInstanceTag\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBMuteInstanceTag\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBIndex1\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBIndex2\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBHasMute\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBHasLevel\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsMic\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseAbsoluteValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUnmuteOnVolChange\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBIncrementAmount\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBPermissions\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "uint? \fBBridgeIndex\fP\fC [get, set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Biamp Tesira Essentials Plugin from the source code\&.
