.TH "Tesira_DSP_EPI.TesiraDsp.QueuedCommand" 3 "Wed Aug 5 2020" "Version 2.0.0.x" "Biamp Tesira Essentials Plugin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tesira_DSP_EPI.TesiraDsp.QueuedCommand \- Contains all data for a component command  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCommand\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBAttributeCode\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "ISubscribedComponent \fBControlPoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains all data for a component command 



.SH "Author"
.PP 
Generated automatically by Doxygen for Biamp Tesira Essentials Plugin from the source code\&.
